# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c16c358ec062411f70db3e36eea560f08704a0342f807e6637323f208d100d999a38c13a4626655d42885d10766930b10494d70bc86a252d60501abd6824428

test:
  secret_key_base: d627bc79dd51ce18322503cc4c1fa483312393a525cede12cb4318887e439e8d285ab4a394c210e3191b1e6affced40f79c1ddf09e9b30eef9cc484167bda39f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
